name: Run Make New Friends - Weekly

on:
  schedule:
    - cron: "0 9 * * 1" # 매주 월요일 9시
  workflow_dispatch:

jobs:
  run-weekly-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Set env
        run: |
          echo "USER_TOKEN=${{ secrets.USER_TOKEN }}" >> .env

      - name: Run weekly script
        run: |
          echo "Weekly script execution started at: $(date -u)"
          npx ts-node src/api/unfollowUsers.ts
          echo "Weekly script execution ended at: $(date -u)"
